### ISSUE TITLE
Broadlink RMPro+ 'learn' RF not working

### ISSUE THREAD

**Issue by GeorgeLee888** [mlfunston/node-red-contrib-broadlink#27]
When learning, the orange light is on.  Long press the remote control and then single-click, but the orange light just flashes for a while, or the orange light remains on all the time,. and the "Broadlink Timeout Received-Closing Device Connection" is displayed repeatedly in the debug field.

4 Apr 16:38:07 - [info] Node-RED version: v0.20.8
4 Apr 16:38:07 - [info] Node.js  version: v10.16.3
4 Apr 16:38:07 - [info] Linux 4.19.97+ arm LE
4 Apr 16:38:12 - [info] Loading palette nodes
4 Apr 16:38:48 - [info] Dashboard version 2.19.4 started at /ui
.........
4 Apr 17:18:46 - [warn] [RM:RM3p] Please keep long press on the remote button until scan finishes.
4 Apr 17:18:51 - [warn] [RM:RM3p] Please tap the remote button.
4 Apr 17:19:15 - [warn] [RM:RM3p] Broadlink Timeout Received - Closing Device Connection
4 Apr 17:19:16 - [warn] [RM:RM3p] Broadlink Timeout Received - Closing Device Connection
4 Apr 17:19:16 - [warn] [RM:RM3p] Broadlink Timeout Received - Closing Device Connection
4 Apr 17:19:17 - [warn] [RM:RM3p] Broadlink Timeout Received - Closing Device Connection
......

Discover  : 
typeid: "279d"
type: "RM2 Pro Plus3"

Thank You !

**Comment by alekob** [comment]
The same here: after managing to setup the e-Control app, learning still doesn't work with node-red-contrib-broadlink-control 2.0.0

Apr  4 16:30:12 daemon.info node-red[14895]: Node-RED version: v1.0.4
Apr  4 16:30:12 daemon.info node-red[14895]: Node.js  version: v10.19.0
Apr  4 16:30:12 daemon.info node-red[14895]: Linux 4.19.105 arm LE
Apr  4 16:30:13 daemon.info node-red[14895]: Loading palette nodes
Apr  4 16:30:16 daemon.info node-red[14895]: Dashboard version 2.20.0 started at /addons/red/ui
...
Apr  4 16:34:28 daemon.warn node-red[14895]: [RM:RMPro] Please keep long press on the remote button until scan finishes.
Apr  4 16:34:37 daemon.warn node-red[14895]: [RM:RMPro] Please tap the remote button.
Apr  4 16:34:58  daemon.warn node-red[14895]: [RM:RMPro] Broadlink Timeout Received - Closing Device Connection
...
Discover node:
{"mac":"...","ip":"...","typeid":"279d","type":"RM2 Pro Plus3"}

**Comment by mlfunston** [comment]
I have pushed a new version 2.0.1 with improved messaging. Can you see if this works for you?
The timeout isn't actually a timeout reading the data, it's a normal close function which had the wrong level assigned.
I don't have an RM Pro / RF unit to test with.
Did the older version of the library work at all, or was it never working in the past with the RF learning?

**Comment by karmarcharger** [comment]
@mlfunston its still showing version 2.0.0
![image](https://user-images.githubusercontent.com/10364143/79707887-80a0b880-82f0-11ea-9b24-c3fd722d8b7e.png)
![image](https://user-images.githubusercontent.com/10364143/79707905-8a2a2080-82f0-11ea-869f-d0a6a22e36f6.png)

**Comment by mlfunston** [comment]
I have requested a refresh but nothing has updated yet in flows.nodered.org. The updated nodes have been published 3 days ago in Github and NPM.

**Comment by mlfunston** [comment]
Looks like it has updated now

**Comment by mlfunston** [comment]
@karmarcharger - Did the new version work?

**Comment by elhaqksa** [comment]
> @mlfunston - Did the new version work?

No, It's not working on RM4 Pro. could you please fix it? it shows 

> Broadlink: RF Scan - Please keep long press on the remote button until scan finishes.

but nothing happened and there is no pairing light form the device.

**Comment by mlfunston** [comment]
Ok, I don't have an RM4 Pro unit to test with so that will be a little difficult right now.

**Comment by alekob** [comment]
Discover node for v2.1.1 returns:
{"mac":"a.b.c.d","ip":"1.2.3.4","typeid":"279d","type":"RM2 Pro Plus3","name":"智能遥控","cloud":false,"msgdata":[0,0,0,0,0,0,0,0,0,0,0,0,120,0,55,17,20,1,4,4,0,0,0,0,192,168,178,40,142,224,0,0,246,211,0,0,0,0,7,0,0,0,0,0,0,0,0,0,189,223,66,126,157,39,33,178,168,192,120,15,119,253,102,108,230,153,186,232,131,189,233,129,165,230,142,167,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}

Learning **RF** codes result in

Broadlink: **IR** Scan - Please tap the remote button within 30 seconds.

... but no codes are learned. Learning **RF** seems to be possible via IHC app only

**Comment by karmarcharger** [comment]
@mlfunston  Not working for my RM4pro, same response as @elhaqksa 
It finds the device but the signal learning does not work.

**Comment by mlfunston** [comment]
@alekob @karmarcharger - Does it work ok for IR code learning? I just want to isolate it to a problem with RF code learning only.

**Comment by karmarcharger** [comment]
@mlfunston  IR and RF does not work, might be issue with sharedFiles configuration as its using different app and manually adjusting the values by hand probably resulted in many errors as the json has many other fields to be filled other than the IP MAC and type.

**Comment by mlfunston** [comment]
It's not related to the catalog file. When you do a learn it does not use it. It just sends the data out on the message payload from the RM node. So can you test an IR learn and see if you can get any data.

**Comment by alekob** [comment]
IR learning works, but RF doesn't  (checked multiple times)

**Comment by GeorgeLee888** [comment]
Discover node for v2.1.1 returns:
[{"mac":"34ea34444445","ip":"192.168.8.29","typeid":"279d","type":"RM2 Pro Plus3","name":"智能遥控\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002","cloud":false,"msgdata":[0,0,0,0,0,0,0,0,0,0,0,0,120,0,0,12,20,3,6,4,0,0,0,0,192,168,8,30,29,128,0,0,71,207,0,0,0,0,7,0,0,0,0,0,0,0,0,0,47,19,102,28,157,39,29,8,168,192,52,234,52,68,68,69,230,153,186,232,131,189,233,129,165,230,142,167,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0]}]

IR learning works, but RF doesn't .

**Comment by mlfunston** [comment]
Ok thanks so I can focus the effort on that section of the code to see if we can work it out. Has anyone got an earlier RM2Pro to test if RF learn is working on that with the current code?

**Comment by GeorgeLee888** [comment]
Discover node for v2.1.1 returns:
[{"mac":"34ea34c73cdb","ip":"192.168.8.31","typeid":"272a","type":"RM2 Pro Plus","name":"智能遥控\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002","cloud":false,"msgdata":[0,0,0,0,0,0,0,0,0,0,0,0,120,0,18,19,20,3,6,4,0,0,0,0,192,168,8,30,8,161,0,0,107,208,0,0,0,0,7,0,0,0,0,0,0,0,0,0,81,6,155,49,42,39,31,8,168,192,52,234,52,199,60,219,230,153,186,232,131,189,233,129,165,230,142,167,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0]}]

IR/RF learning works,

**Comment by mlfunston** [comment]
@GeorgeLee888 @karmarcharger @alekob @elhaqksa - I have created a new branch with a possible fix and increased debug logging here: https://github.com/mlfunston/node-red-contrib-broadlink-control/tree/RF-Scan-Fix

If someone can download it and link it in and test it and see if it fixes the issue that would be great. There is increased logging going into the node red log, so you can see that when running `node-red-log` and share the log too please.

**Comment by GeorgeLee888** [comment]
Broadlink: RF Scan - Sending RF Sweep Command.
6 May 23:39:03 - [warn] [RM:RM3p] Broadlink: RF Scan - Please hold down a button on the RF Remote until scan finishes.
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 01>
Broadlink: Valid RF Signal Received - RF Signal Locked - Sending Notice to Proceed.
6 May 23:39:07 - [warn] [RM:RM3p] Broadlink: Please tap the remote button.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
6 May 23:39:32 - [info] [RM:RM3p] Broadlink: Closing Device Connection

**Comment by GeorgeLee888** [comment]
Broadlink: RF Scan - Sending RF Sweep Command.
6 May 23:43:06 - [warn] [RM:RM3p] Broadlink: RF Scan - Please hold down a button on the RF Remote until scan finishes.
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 01>
Broadlink: Valid RF Signal Received - RF Signal Locked - Sending Notice to Proceed.
6 May 23:43:11 - [warn] [RM:RM3p] Broadlink: Please tap the remote button.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
6 May 23:43:36 - [info] [RM:RM3p] Broadlink: Closing Device Connection

typeid: "279d"
type: "RM2 Pro Plus3"

**Comment by GeorgeLee888** [comment]
Broadlink: RF Scan - Sending RF Sweep Command.
6 May 23:45:16 - [warn] [RM:RM3p] Broadlink: RF Scan - Please hold down a button on the RF Remote until scan finishes.
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 01>
Broadlink: Valid RF Signal Received - RF Signal Locked - Sending Notice to Proceed.
6 May 23:45:18 - [warn] [RM:RM3p] Broadlink: Please tap the remote button.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
6 May 23:45:46 - [info] [RM:RM3p] Broadlink: Closing Device Connection

typeid: "279d"
type: "RM2 Pro Plus3"

**Comment by mlfunston** [comment]
Ok so the RF learning works now on the RM2 Pro Plus 3?

> Discover node for v2.1.1 returns:
> [{"mac":"34ea34c73cdb","ip":"192.168.8.31","typeid":"272a","type":"RM2 Pro Plus","name":"智能遥控\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002","cloud":false,"msgdata":[0,0,0,0,0,0,0,0,0,0,0,0,120,0,18,19,20,3,6,4,0,0,0,0,192,168,8,30,8,161,0,0,107,208,0,0,0,0,7,0,0,0,0,0,0,0,0,0,81,6,155,49,42,39,31,8,168,192,52,234,52,199,60,219,230,153,186,232,131,189,233,129,165,230,142,167,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0]}]
> 
> **IR/RF learning works,**

The console log seems odd as it seems to be missing the log lines for lines 11&12 in RM.js. Strange.
https://github.com/mlfunston/node-red-contrib-broadlink-control/blob/82a1113b19d21b074cd2ca8ae51ff9f994e041f7/nodes/RM.js#L11

**Comment by GeorgeLee888** [comment]
Broadlink: RF Scan - Sending RF Sweep Command.
7 May 16:19:19 - [warn] [RM:RM3p] Broadlink: RF Scan - Please hold down a button on the RF Remote until scan finishes.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 19 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 01>
Broadlink: Valid RF Signal Received - RF Signal Locked - Sending Notice to Proceed.
7 May 16:19:23 - [warn] [RM:RM3p] Broadlink: Please tap the remote button.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
7 May 16:19:49 - [info] [RM:RM3p] Broadlink: Closing Device Connection

typeid: "279d"
type: "RM2 Pro Plus3"
"RM2 Pro Plus 3 " RF not working.

**Comment by GeorgeLee888** [comment]
Broadlink: RF Scan - Sending RF Sweep Command.
7 May 17:59:02 - [warn] [RM:RM4p] Broadlink: RF Scan - Please hold down a button on the RF Remote until scan finishes.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 19 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 01>
Broadlink: Valid RF Signal Received - RF Signal Locked - Sending Notice to Proceed.
7 May 17:59:13 - [warn] [RM:RM4p] Broadlink: Please tap the remote button.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
7 May 17:59:32 - [info] [RM:RM4p] Broadlink: Closing Device Connection

typeid: "6026"
type: "RM4 Pro"
name: "智能遥控"
cloud: false

IR learning works, but RF doesn't .

**Comment by GeorgeLee888** [comment]
Learning with RM3, sending with RM4 is good, but the learning code cannot be too short

**Comment by GeorgeLee888** [comment]
RF Learning with "RM2 Pro Plus(272a)", sending with RM4 Pro (6026) is good.

RF Learning with "RM2 Pro Plus" Data :
[178,0,202,0,12,24,11,24,11,25,11,24,12,24,23,12,12,24,23,13,11,24,24,12,11,24,24,12,12,23,24,12,12,24,23,0,1,1,159,49,23,12,24,12,24,11,24,12,24,12,11,24,12,24,11,24,12,24,23,12,24,12,23,13,11,24,24,11,12,24,24,12,11,24,12,24,12,23,24,12,24,12,12,23,24,12,23,13,11,24,12,24,11,24,12,24,12,23,24,12,11,25,23,12,12,24,23,12,12,24,23,12,12,24,23,12,12,24,24,0,1,0,158,49,24,12,23,12,24,12,23,13,23,12,12,24,12,23,12,24,11,24,24,12,23,12,24,12,11,24,24,12,11,24,24,12,11,24,12,24,12,23,24,12,23,13,11,24,23,13,23,12,12,24,12,23,12,24,12,24,11,24,23,13,12,23,24,12,12,23,24,12,12,23,24,12,12,23,24,12,12,24,23,0,5,220,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
sending with RM2 Pro Plus Log(typeid: "272a"):
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 02 00 00 00 b2 00 ca 00 0c 18 0b 18 0b 19 0b 18>
Broadlink: Success Data Received - Type 2 Data Successful.

sending with RM4 Pro Log(typeid: "6026"):
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Success Data Received - Type 2 Data Successful.

**Comment by GeorgeLee888** [comment]
Broadlink: RF Scan - Sending RF Sweep Command.
9 May 22:58:20 - [warn] [RM:RM4p] Broadlink: RF Scan - Please hold down a button on the RF Remote until scan finishes.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 19 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 01>
Broadlink: Valid RF Signal Received - RF Signal Locked - Sending Notice to Proceed.
9 May 22:58:31 - [warn] [RM:RM4p] Broadlink: Please tap the remote button.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
9 May 22:58:50 - [info] [RM:RM4p] Broadlink: Closing Device Connection

typeid: "6026"
type: "RM4 Pro"
name: "智能遥控"
cloud: false

**Comment by GeorgeLee888** [comment]
Broadlink: RF Scan - Sending RF Sweep Command.
10 May 00:39:03 - [warn] [RM:RM3p] Broadlink: RF Scan - Please hold down a button on the RF Remote until scan finishes.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 19 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - Checking if RF Signal Detected.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1a 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 26 Converting and Sending.
payload <Buffer 1a 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 01>
Broadlink: Valid RF Signal Received - RF Signal Locked - Sending Notice to Proceed.
10 May 00:39:06 - [warn] [RM:RM3p] Broadlink: Please tap the remote button.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: Data Received - Determining Type.
Broadlink: BroadlinkData <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
Broadlink: Data Received - Type 27 Converting and Sending.
payload <Buffer 1b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>
data <Buffer 00>
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
Broadlink: RF Scan - RF Signal Detected, capturing button data.
10 May 00:39:33 - [info] [RM:RM3p] Broadlink: Closing Device Connection

typeid: "279d"
type: "RM2 Pro Plus3"
name: "智能遥控"
cloud: false

**Comment by quadhammer** [comment]
272a
RM2 Pro Plus

Using version 2.1.1 works to learn both IR and RF for me, thanks!

The only problem I had was using colons is in the MAC address of the rmdevice configuration node gave me an error about not being configured properly on deployment, despite it still working.  

Thanks again.

**Comment by Leon99** [comment]
Learning doesn't work for me. With RF Sweep enabled, the yellow indicator turns on and then blinks for a moment after I press and hold the button, but tapping the button after that doesn't cause any reaction. Without RF Sweep it just turns on for a while.
ihc app works just fine. broadlink_cli from python-broadlink also works fine (using `--rfscanlearn`)

broadlink-control v. 2.1.1
typeid: "27a9"
type: "RM2 Pro Plus300"
Firmware v43

**Comment by alekob** [comment]
Learning still doesn't work for me, but with "broadlink_cli" (thanks for mentioning @Leon99 ) RF codes can be learned. The detected RF codes can then be used in NR

**Comment by kukudemajia** [comment]
Learning of RF code  still doesn't work for me.Device type is 272a.
node-red-contrib-broadlink-control 2.1.4
Sometimes I can learn the RF code like lists(buffer object[38,0,140......,0,0]) and then Send those out directly.
It dosen't work.

**Comment by Moltey** [comment]
It has been a while since this issue has been discovered. I also had difficulties with reading the RF codes from my Broadlink Pro+ device with node-red.

I found my relief in another project: 
https://github.com/t0mer/broadlinkmanager-docker

Reading the RF codes works like charm with broadlinkmanager - just copy the Code to node-red and continue with your flows.

Maybe this is also helpful for other users and may also the solution for this issue.
